controllers:
  resource: ../../src/
  type: annotation

#Test
private_api_request_context:
  resource: '../../src/RequestContext/Infrastructure/Controller/PrivateApi'
  prefix: /private/request
  type: annotation