controllers:
  resource: ../../src/
  type: annotation

#Test
private_api_request_context:
  resource: '../../src/RequestContext/Infrastructure/Controller/PrivateApi/v1'
  prefix: /private/request/v1
  type: annotation